apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: rh-push-to-registry-redhat-iotest-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rh-push-to-registry-redhat-iotest-component
    app.kubernetes.io/part-of: rh-push-to-registry-redhat-iotest
  name: rh-push-to-registry-redhat-iotest-component
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: python-app
      app.kubernetes.io/instance: rh-push-to-registry-redhat-iotest-component
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-app
        app.kubernetes.io/instance: rh-push-to-registry-redhat-iotest-component
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/dev-release-team-tenant/rh-push-to-registry-redhat-iotest/rh-push-to-registry-redhat-iotest-component@sha256:f088e615b611cd14c29d7f1363480889bbb8ee06a81177295d1110de57d5e6b9
        name: my-python
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
